/*
	Autogenerated file. Do not edit 
 */
#ifndef 	CONFIG_H
#define 	CONFIG_H
#define INSTPATH 	"/home/gmack/gcom"
#define EXECUTABLE 	"admind"
#define CONFIG 		"/home/gmack/gcom/conf/admind.conf"
#define LOG 		"/home/gmack/gcom/logs/admind.log"
#define DEBUGLOG 	"/home/gmack/gcom/logs/admind_debug.log"
#define PIDFILE 	"/home/gmack/gcom/run/admind.pid"
#endif 		/* CONFIG_H */
